- name: Provision laptop
  hosts: Laptops
  gather_facts: no
  vars:
    software_packages_endpoint: "xxx"
    provisioning_base: "C:\\MA_PROVISIONING"
    provisioning_scripts: "{{ provisioning_base }}\\scripts"

    arcgis_store: "{{ provisioning_base }}\\ArcGISPro"
    arcgis_exe: "{{ arcgis_store }}\\installer.exe"
    arcgis_msi: "{{ arcgis_store }}\\ArcGIS Pro 3.4\\ArcGISPro\\ArcGISPro.msi"
    arcgis_patch_1: "ArcGIS_Pro_341_192917.msp"
    arcgis_patch_2: "ArcGIS_Pro_342_192916.msp"
    arcgis_toolbar: "MapActionToolbars_3_4_2_5.esriAddinX"
    arcgis_add_ins_path: "{{ arcgis_store }}\\add-ins"
    arcgis_base: "C:\\Program Files\\ArcGIS\\Pro"
    arcgis_conda: "{{ arcgis_base }}\\bin\\Python\\Scripts\\conda.exe"
    arcgis_env_utils: "{{ arcgis_base }}\\bin\\PythonEnvUtils.exe"
    arcgis_env_base: "arcgispro-py3"
    arcgis_env_ma: "mapaction-arc-py3"

    office_key: "xxx"

    fonts_base: "{{ provisioning_base }}\\Fonts"
    font_installer: "{{ provisioning_scripts }}\\install-font.ps1"

  tasks:
    - name: Create provisioning scripts directory
      win_file:
        path: "{{ provisioning_scripts }}"
        state: directory
    - name: Install Chocolatey package manager
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey
        state: present

    - name: Install Microsoft Office productivity suite (slow)
      chocolatey.chocolatey.win_chocolatey:
        name: office2019proplus
        package_params: "/Language=en-us"
        state: present
    - name: Check current Office product key
      win_shell: cscript "C:\Program Files\Microsoft Office\Office16\OSPP.VBS" /dstatus
      register: office_dstatus
      changed_when: false
    - name: Remove default Office product key
      win_shell: >
        cscript "C:\Program Files\Microsoft Office\Office16\OSPP.VBS"
        /unpkey:{{ office_dstatus.stdout | regex_search('Last 5 characters of installed product key: (\w{5})', '\1') | first }}
      when:
        - office_key[-5:] not in office_dstatus.stdout
    - name: Set Office product key
      win_shell: cscript "C:\Program Files\Microsoft Office\Office16\OSPP.VBS" /inpkey:{{ office_key }}
      when: office_key[-5:] not in office_dstatus.stdout

    - name: Install .Net desktop runtime for ArcGIS Pro
      chocolatey.chocolatey.win_chocolatey:
        name: dotnet-8.0-desktopruntime
        state: present
    - name: Create ArcGIS Pro install directory
      win_file:
        path: "{{ arcgis_store }}"
        state: directory
    - name: Download ArcGIS Pro installer (slow)
      win_get_url:
        url: "{{ software_packages_endpoint }}/software/arcgis-pro/3.4.2/ArcGISPro_34_192912.exe"
        dest: "{{ arcgis_exe }}"
        checksum: "228fba5c8b82aafdd2444b0cfc48a51aaa6cb7b7"
        force: false
    - name: Extract ArcGIS Pro installer
      win_command: '{{ arcgis_exe }} /s /d {{ arcgis_store }}'
      args:
        creates: '{{ arcgis_msi }}'
    - name: Install ArcGIS Pro geospatial editor (slow)
      win_package:
        path: '{{ arcgis_msi }}'
        arguments: 'ALLUSERS=1 ACCEPTEULA=YES ADDLOCAL=SemanticSearch,ToolSuggestions BLOCKADDINS=0 CHECKFORUPDATESATSTARTUP=0 SOFTWARE_CLASS=Professional'
        state: present
    - name: Download ArcGIS Pro patch 1
      win_get_url:
        url: "{{ software_packages_endpoint }}/software/arcgis-pro/3.4.2/{{ arcgis_patch_1 }}"
        dest: "{{ arcgis_store }}\\{{ arcgis_patch_1 }}"
        checksum: "1d80c908125efdd241dfc454f3fd101a83820425"
        force: false
    - name: Install ArcGIS Pro patch 1
      win_package:
        path: '{{ arcgis_store }}\\{{ arcgis_patch_1 }}'
        arguments: 'REINSTALLMODE=omus REINSTALL=ALL'
        state: present
    - name: Download ArcGIS Pro patch 2
      win_get_url:
        url: "{{ software_packages_endpoint }}/software/arcgis-pro/3.4.2/{{ arcgis_patch_2 }}"
        dest: "{{ arcgis_store }}\\{{ arcgis_patch_2 }}"
        checksum: "b46f5df75dfaaba43d6340f06f3fb1a9aee2ed5c"
        force: false
    - name: Install ArcGIS Pro patch 2
      win_package:
        path: '{{ arcgis_store }}\\{{ arcgis_patch_2 }}'
        arguments: 'REINSTALLMODE=omus REINSTALL=ALL'
        state: present
    - name: Create ArcGIS Pro add-ins directory
      win_file:
        path: "{{ arcgis_add_ins_path }}"
        state: directory
    - name: Download MapAction toolbar ArcGIS Pro add-in
      win_get_url:
        url: "{{ software_packages_endpoint }}/software/mapaction-toolbar-arcgis-pro/3.4.2.5/{{ arcgis_toolbar }}"
        dest: "{{ arcgis_add_ins_path }}\\{{ arcgis_toolbar }}"
        checksum: "782dada04b9a415f69f5564a067b75a763814143"
        force: false
    - name: Set ArcGIS Pro add-ins search path
      win_regedit:
        path: "HKCU:\\Software\\ESRI\\ArcGISPro\\Settings\\Add-In Folders"
        name: "{{ arcgis_add_ins_path }}"
        state: present
    - name: Create MapAction ArcGIS Pro conda environment (slow)
      win_command: '"{{ arcgis_conda }}" create -n {{ arcgis_env_ma }} --yes --clone {{ arcgis_env_base }}'
      args:
        creates: '{{ arcgis_base }}\\bin\\Python\\envs\\{{ arcgis_env_ma }}'
    - name: Get active ArcGIS Pro conda environment
      win_command: '"{{ arcgis_env_utils }}"'
      register: arcgis_active_env
      changed_when: false
    - name: Switch ArcGIS Pro conda environment to MapAction
      win_command: '"{{ arcgis_conda }}" proswap -n {{ arcgis_env_ma }}'
      when: arcgis_env_ma not in arcgis_active_env.stdout
    - name: Install GeoPandas into MapAction ArcGIS Pro conda environment (slow)
      win_command: '"{{ arcgis_conda }}" install -n {{ arcgis_env_ma }} --yes geopandas'
      args:
        creates: '{{ arcgis_base }}\\bin\\Python\\envs\\{{ arcgis_env_ma }}\\Lib\\site-packages\\geopandas'
    - name: Install QGIS geospatial editor (slow) 
      chocolatey.chocolatey.win_chocolatey:
        name: qgis-ltr
        state: present
        version: 3.44.9
    - name: Install Adobe Reader PDF viewer
      chocolatey.chocolatey.win_chocolatey:
        name: adobereader
        state: present
    - name: Install Chrome web browser
      chocolatey.chocolatey.win_chocolatey:
        name: googleChrome
        ignore_checksums: true
        state: present
    - name: Install Firefox web browser
      chocolatey.chocolatey.win_chocolatey:
        name: Firefox
        state: present
    - name: Install PDFsam PDF editing tool
      chocolatey.chocolatey.win_chocolatey:
        name: pdfsam
        state: present
    - name: Install Nextcloud file sync client
      chocolatey.chocolatey.win_chocolatey:
        name: nextcloud-client
        state: present
    - name: Install VLC media player
      chocolatey.chocolatey.win_chocolatey:
        name: vlc
        state: present
    - name: Install 7-Zip file archiver
      chocolatey.chocolatey.win_chocolatey:
        name: 7zip
        state: present
    - name: Install Slack messenger
      chocolatey.chocolatey.win_chocolatey:
        name: slack
        state: present
    - name: Install Google Earth Pro geospatial viewer 
      chocolatey.chocolatey.win_chocolatey:
        name: googleearthpro
        state: present
    - name: Install Notepad++ text editor
      chocolatey.chocolatey.win_chocolatey:
        name: notepadplusplus
        state: present
    - name: Install VSCode code editor
      chocolatey.chocolatey.win_chocolatey:
        name: vscode
        state: present
    - name: Install Google Drive file sync client
      chocolatey.chocolatey.win_chocolatey:
        name: googledrive
        ignore_checksums: true
        state: present
    - name: Install WinDirStat disk usage analyser
      chocolatey.chocolatey.win_chocolatey:
        name: windirstat
        state: present
    - name: Install InkScape vector graphics editor
      chocolatey.chocolatey.win_chocolatey:
        name: inkscape
        state: present
    - name: Install GIMP raster graphics editor
      chocolatey.chocolatey.win_chocolatey:
        name: gimp
        state: present
    - name: Install PowerBI dashboards editor
      chocolatey.chocolatey.win_chocolatey:
        name: powerbi
        ignore_checksums: true
        state: present
    - name: Install Microsoft Teams messenger
      chocolatey.chocolatey.win_chocolatey:
        name: microsoft-teams-new-bootstrapper
        state: present
    - name: Install Signal messenger
      chocolatey.chocolatey.win_chocolatey:
        name: signal
        state: present

    - name: Copy font installation helper script
      win_copy:
        src: "files/install-font.ps1"
        dest: "{{ font_installer }}"
    - name: Create provisioning fonts directory
      win_file:
        path: "{{ fonts_base }}"
        state: directory
    - name: Download Roboto fonts
      win_get_url:
        url: "{{ software_packages_endpoint }}/fonts/Roboto/{{ item.name }}"
        dest: "{{ fonts_base }}\\{{ item.name }}"
        checksum: "{{ item.sum }}"
        force: false
      with_items:
        - { name: "Roboto-VariableFont-wdth-wght.ttf", sum: "126465ccaecd3fc5588ad03d1b131ee46e617813" }
        - { name: "Roboto-Italic-VariableFont-wdth-wght.ttf", sum: "b5f0683b0e93f960e7f0796d8812d7fe92f56e93" }
    - name: Install Roboto fonts
      win_shell: 'powershell.exe -ExecutionPolicy Bypass -File "{{ font_installer }}" "{{ fonts_base }}\{{ item }}"'
      args:
        creates: "C:\\Windows\\Fonts\\{{ item }}"
      with_items:
        - "Roboto-VariableFont-wdth-wght.ttf"
        - "Roboto-Italic-VariableFont-wdth-wght.ttf"
    - name: Download Humanitarian Icons font
      win_get_url:
        url: "{{ software_packages_endpoint }}/fonts/Humanitarian-Icons/Humanitarian-Icons.ttf"
        dest: "{{ fonts_base }}\\Humanitarian-Icons.ttf"
        checksum: "f938bbef923d90e0d462246439a060b8ed05b858"
        force: false
    - name: Install Humanitarian Icons font
      win_shell: 'powershell.exe -ExecutionPolicy Bypass -File "{{ font_installer }}" "{{ fonts_base }}\Humanitarian-Icons.ttf"'
      args:
        creates: "C:\\Windows\\Fonts\\Humanitarian-Icons.ttf"